version: '3.8'

services:
  nginx:
    container_name: cpp-nginx
    restart: unless-stopped
    image: nginx:1.23.0-alpine
    ports:
      - ${DOCKER_APP_IP}:80:80
    volumes:
      - ./docker/nginx/conf.d/blog.conf:/etc/nginx/conf.d/blog.conf
      - ./:/var/www
    depends_on:
      - php

  php:
    container_name: cpp-php
    restart: unless-stopped
    image: srgiz/cpp-php:latest
    build:
      context: ./docker/php
    environment:
      PS1: "\\u:\\w$$ "
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
      - ./:/var/www

networks:
  default:
    name: php-cpp.local
